Add e2e tests
nestjs-addons/in-memory-db pull request #60
Opened 2019-08-26 00:00 UTC by jordanpowell88

This isn't ready to merge but it is a starting point. Their are 2 issues currently that I know need resolved.

1.) I don't have the import alias working
2.) The e2e tests for the async methods appear to be returning T instead of an Observable<T>. The methods appear to be fine and the unit tests are passing but the issue is getting the response via an http request.

2019-08-28 17:41 UTC, jordanpowell88 commented
@wesleygrimes did you want me to try to get these tests to run from root or did we want to look into adding nx?

2019-08-28 23:22 UTC, jordanpowell88 commented
I am able to run tests in the root of the project locally just fine. Not sure why it says it can't find supertest even though it is a devDependency. ![Screen Shot 2019-08-28 at 7 21 20 PM](https://user-images.githubusercontent.com/3605268/63898967-120d9400-c9c9-11e9-9c1a-2394134fa5a9.png)

2019-08-30 00:55 UTC, wesleygrimes commented
Let’s pair on this tomorrow

2019-08-30 00:56 UTC, jordanpowell88 commented
Sounds good

2019-09-06 00:16 UTC, wesleygrimes requested changes
Need to add coverage folder to nested .gitignore

2019-09-09 15:20 UTC, wesleygrimes commented
Looks like the files were added to the .gitignore, but not actually removed from the commit. Can you rebase on master?

2019-09-20 13:13 UTC, jordanpowell88 commented
I have another branch that has e2e tests for using forFeature and forRoot as well

2019-09-23 20:15 UTC, itayod reviewed
@jordanpowell88 Nicely done!! great work 👍

2019-09-23 20:15 UTC, itayod commented on e2e/test-app/README.md
> +<p align="center">
Do we need this README file?

2019-09-23 20:15 UTC, itayod commented on e2e/test-app/coverage/clover.xml
> +<?xml version="1.0" encoding="UTF-8"?>
please remove all files under `e2e/test-app/coverage` :)

2019-09-23 23:31 UTC, jordanpowell88 commented on e2e/test-app/README.md
> +<p align="center">
Probably not, I can remove it

2019-09-25 00:33 UTC, closed without merging