Feature/auto generated controller
nestjs-addons/in-memory-db pull request #96
Opened 2019-10-02 19:44 UTC by itayod

close #73

2019-10-02 22:31 UTC, jordanpowell88 requested changes
This looks great! 2 things I noticed,

- Do we want to make a BaseEntityController for both Async and Sync methods?

- We should add a controller that extends this in the e2e project

2019-10-03 16:35 UTC, wesleygrimes requested changes
Looks good! Just a couple things.

2019-10-03 16:35 UTC, wesleygrimes commented on lib/controllers/in-memory-db.controller.ts
> +export abstract class InMemoryDbEntityController<T extends InMemoryDBEntity> {
```suggestion
export abstract class InMemoryDbEntityAsyncController<T extends InMemoryDBEntity> {
```


create a second one that uses the sync methods and is called `InMemoryDbEntityController`

2019-10-07 08:23 UTC, itayod commented
LGTM, @wesleygrimes @jordanpowell88 could you take another look?

2019-10-07 13:27 UTC, wesleygrimes requested changes
Looking good!

Can you add some documentation to the `README.md` that shows how to implement a new controller that extends from both the Async and Sync versions? Want to make sure to show how to pass in an `InMemoryDBService` that is forRoot and one that is for a specific feature that was injected into the controller's constructor using `InjectInMemoryDB`

2019-10-07 13:31 UTC, itayod commented
> Looking good!
> 
> Can you add some documentation to the `README.md` that shows how to implement a new controller that extends from both the Async and Sync versions? Want to make sure to show how to pass in an `InMemoryDBService` that is forRoot and one that is for a specific feature that was injected into the controller's constructor using `InjectInMemoryDB`

2019-10-07 16:11 UTC, wesleygrimes requested changes
Added comments

2019-10-07 16:11 UTC, wesleygrimes commented on README.md
> +## Table of Content
```suggestion
## Table of Contents
```

2019-10-07 16:11 UTC, wesleygrimes commented on README.md
> +In order to prevent code duplication and boilerplate for each controller, we created two base entity controllers `InMemoryDbEntityController` and `InMemoryDbEntityAsyncController`.
```suggestion
In order to prevent code duplication and boilerplate for each controller, we have created two base entity controllers `InMemoryDbEntityController` and `InMemoryDbEntityAsyncController`. This allows you to quickly provide endpoints to make requests without having to manually implement each action.
```

2019-10-07 16:11 UTC, wesleygrimes commented on README.md
> +To use the controllers, simply create a controller and extend it with one of the controllers.
```suggestion
To use the controllers, simply create a new controller and extend it with one of the provided base controllers.
```

2019-10-07 16:11 UTC, wesleygrimes commented on README.md
> +Of course, it will also be possible to use an Entity Controller with a specific feature service by using the decorator `InjectInMemoryDBService`
```suggestion
In order to have an Entity Controller use a feature-specific instance of the service, use the decorator `InjectInMemoryDBService` in the controller's provided by this library as shown below:
```

2019-10-07 23:38 UTC, wesleygrimes approved these changes
LGTM

2019-10-07 23:41 UTC, merged

2019-10-07 23:43 UTC, wesleygrimes commented
:tada: This PR is included in version 1.8.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@nestjs-addons/in-memory-db)
- [GitHub release](https://github.com/nestjs-addons/in-memory-db/releases/tag/v1.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2019-10-10 10:19 UTC, wesleygrimes commented
@all-contributors please add @itayod for code, tests, docs